jenkins:
  systemMessage: "Controlled by Configuration as Code"
jobs:
  - script: >
      multibranchPipelineJob('react-jte') {
          branchSources {
              git {
                  id = 'configuration-as-code'
                  remote('https://github.com/undefspi/react-web-app.git')
              }
          }
          configure { 
               def mbProject = it
               def props = mbProject / 'properties'
               def bz = mbProject / 'org.boozallen.plugins.jte.config.TemplateConfigFolderProperty' / 'tier'
               bz / configurationProvider(class: 'hudson.plugins.git.GitSCM' plugin='git@3.9.3'
          }
      }
