jenkins:
  systemMessage: "Controlled by Configuration as Code"
jobs:
  - script: >
      multibranchPipelineJob('react-jte') {
          branchSources {
              git {
                  id = 'configuration-as-code'
                  remote('https://github.com/undefspi/react-web-app.git')
              }
          }
          properties {
              configure { node ->
                  node / healthMetrics / 'com.cloudbees.hudson.plugins.folder.health.WorstChildHealthMetric'
              }
          }
      }
