jenkins:
  systemMessage: "Controlled by Configuration as Code"
jobs:
  - script: >
      multibranchPipelineJob('react-jte') {
          branchSources {
              git {
                  id = 'configuration-as-code'
                  remote('https://github.com/undefspi/react-web-app.git')
              }
          }
          configure { node ->
            node / properties / 'org.boozallen.plugins.jte.config.TemplateConfigFolderProperty' / tier / configurationProvider / scm / userRemoteConfigs / 'hudson.plugins.git.UserRemoteConfig' / url { 
                'https://github.com/undefspi/react-web-app.git' 
            }
          }
      }