jenkins:
  systemMessage: "Controlled by Configuration as Code"
jobs:
  - script: >
      multibranchPipelineJob('react-jte') {
          branchSources {
              git {
                  id = 'configuration-as-code'
                  remote('https://github.com/undefspi/react-web-app.git')
              }
          }
          configure { 
               def aNode = it 
               def anotherNode = aNode / 'properties'
          }
      }
