jenkins:
  systemMessage: "Controlled by Configuration as Code"
jobs:
  - script: >
        multibranchPipelineJob('react-jte') {
            branchSources {
                git {
                    id = 'configuration-as-code'
                    remote('https://github.com/undefspi/react-web-app.git')
                }
            }
            configure { 
                def mbProject = it
                def props = mbProject / 'properties' / 'org.boozallen.plugins.jte.config.TemplateConfigFolderProperty'
                props.@plugin = 'templating-engine@1.7.1'
            }
        }
